### ISSUE TITLE
App Crashes When Importing from GitHub

### ISSUE THREAD

**Issue by ctrowbridge** [ctrowbridge/CreateDBScript#1]
When the application is first imported from GitHub, the scripts directory doesn't exist, so the app crashes. The application should not assume that the scripts directory exists.

java.io.FileNotFoundException: scripts\connectDB.sql (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at com.cindy.CreateDBScript.generateConnectScript(CreateDBScript.java:49)
	at com.cindy.CreateDBScript.generateScripts(CreateDBScript.java:34)
	at com.cindy.CreateDBScript.main(CreateDBScript.java:198)
java.io.FileNotFoundException: scripts\createDB.sql (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at com.cindy.CreateDBScript.generateCreateDbScript(CreateDBScript.java:72)
	at com.cindy.CreateDBScript.generateScripts(CreateDBScript.java:35)
	at com.cindy.CreateDBScript.main(CreateDBScript.java:198)
java.io.FileNotFoundException: scripts\loadDB.sql (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileWriter.<init>(Unknown Source)
	at com.cindy.CreateDBScript.generateLoadScript(CreateDBScript.java:106)
	at com.cindy.CreateDBScript.generateScripts(CreateDBScript.java:36)
	at com.cindy.CreateDBScript.main(CreateDBScript.java:198)
<><><><><> CreateDBScript <><><><><>

Generate database connection script ...
Script created "scripts\connectDB.sql"

Generate database creation script ...
Script created "scripts\createDB.sql"

Generate database load script ...
Script created "scripts\loadDB.sql"
Done!

**Comment by ctrowbridge** [comment]
Issue has been fixed - see referenced commits.
